is212-ljps/is212-LJPS

ljps-frontend/util/validation/index.js

3 parameters:
1) string
2) min length
3) max length

added validate length as utility function

---

ljps-frontend/styles/globals.css

updated dark mode css

---

backend/database/ljps_sql_setup.sql

JIRA ticket: No ticket
Replaced Job_Role_ID with Skill_ID in course_skill table.

Fix incorrect skill id in course_skill table

---

.github/pull_request_template.md

[NO-JIRA] Update pull_request_template.md

---

.github/pull_request_template.md

JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-41

[LJPS-41] Changes to PR template

---

.gitignore
backend/database/index.js
backend/src/routes/courses/CoursesRouter.js
backend/src/routes/roles/RolesRouter.js
backend/src/routes/skills/SkillsRouter.js

Fix missing database connection file

---

backend/database/ljps_sql_setup.sql

[NO-JIRA] Fix missing table engine

---

backend/src/routes/courses/CoursesRouter.js
ljps-frontend/pages/learning-journey/view-skills/view-courses/index.js

JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-33

[LJPS-33] View course details

---

backend/database/index.js
backend/package-lock.json
backend/src/routes/skills/SkillsRouter.js
ljps-frontend/components/SkillsComponent/SkillModal.js

- [ x ] My branch is up-to-date with the `main` branch
- [ x ] Unit test written
- [ x ] Acceptance Criteria considered and implemented
Low

LJPS-26 Assign Skills to Courses front-end + back-end

---

ljps-frontend/pages/index.js

Reopened branch to add role and staffID to local storage 
JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-50
No Change in UI

[LJPS-50] added role and staffID to local storage

---

ljps-frontend/components/SkillsComponent/SkillModal.js
ljps-frontend/pages/skill/index.js

1. Fixed a bug when updating skills, that the form will get reset. 
2. Fixed a bug where reopening the same update skill modal will cause form to reset, but opening different skills update modal won't. Now form will not rese.
JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-63

[LJPS-63] Fixed Skills Modal form reset bug

---

backend/database/index.js
backend/service/src/SkillsService.js
backend/src/routes/skills/SkillsRouter.js
ljps-frontend/components/SkillsComponent/createskillbutton.js
ljps-frontend/pages/skill/index.js

JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-20
**Frontend**
- Added Active/Inactive buttons on Skills page
- Updated frontend logic to retrieve skills based on Is_Active status
**Backend**
- Added getInactiveSkills query in index.js
- Added getInactiveSkills into SkillsService layer
- Updated endpoints in SkillsRouter
**Active view**
**Inactive view**

[LJPS-20] View Inactive Skills

---

backend/database/index.js
backend/service/src/RolesService.js
backend/src/routes/roles/RolesRouter.js
ljps-frontend/components/RolesComponent/createrolebutton.js
ljps-frontend/pages/roles/index.js

JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-21
**Frontend**
- Added Active/Inactive buttons on Roles page
- Updated frontend logic to retrieve roles based on Is_Active status
**Backend**
- Added getInactiveRoles query in index.js
- Added getInactiveRoles into RolesService layer
- Updated endpoints in RolesRouter
**Active view**
**Inactive view**

[LJPS-21] View Inactive Roles

---

ljps-frontend/components/SkillsComponent/SkillModal.js

JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-62
Updated frontend logic on SkillModal.js to ensure that for each skill, at least 1 course is assigned to it when trying to create/update skills
**0 Skills selected**

[LJPS-62] Assign Skills to Courses (Revised)

---

.github/pull_request_template.md

[NO-JIRA] Change PR template

---

backend/database/index.js

[NO-JIRA] fix syntax

---

backend/Dockerfile
ljps-frontend/next.config.js

[NO-JIRA] Fix errors

---

ljps-frontend/components/LearningJourneyComponent/Tooltip.js
ljps-frontend/pages/learning-journey/index.js
ljps-frontend/pages/learning-journey/view-skills/index.js

Completed LJPS-49 View Skill Details when creating learning Journey
JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-49
Added tooltip component for view skills page.

[LJPS-49] View Skill Details when creating learning Journey

---

.github/workflows/intTest_merge.yml
.github/workflows/intTest_pr.yml
backend/database/DatabaseDao.js
backend/src/intTest/runTest.sh
ljps-frontend/components/CourseComponent/CourseModal.js
ljps-frontend/components/RolesComponent/RoleModal.js
ljps-frontend/components/RolesComponent/deleterolebutton.js
ljps-frontend/components/SkillsComponent/SkillModal.js
ljps-frontend/components/SkillsComponent/deleteskillbutton.js
ljps-frontend/pages/learning-journey/index.js
ljps-frontend/pages/learning-journey/view-skills/index.js
ljps-frontend/pages/learning-journey/view-skills/view-courses/index.js
ljps-frontend/pages/learning-journey/view/index.js
ljps-frontend/pages/roles/index.js
ljps-frontend/pages/skill/index.js

Ensure that frontend uses env variables so we can deploy with ease
None
Low

[NO-JIRA] Add env variables

---

backend/service/__tests__/CoursesService.test.js
backend/service/__tests__/LearningJourneyService.test.js
backend/service/__tests__/RolesService.test.js
backend/service/__tests__/SkillsService.test.js
backend/service/src/CoursesService.js
backend/service/src/LearningJourneyService.js
backend/service/src/SkillsService.js
backend/src/routes/courses/CoursesRouter.js
backend/src/routes/roles/RolesRouter.js
backend/src/routes/skills/SkillsRouter.js
ljps-frontend/components/CourseComponent/CourseModal.js
ljps-frontend/pages/learning-journey/index.js
ljps-frontend/pages/learning-journey/view-skills/index.js
ljps-frontend/pages/learning-journey/view-skills/view-courses/index.js
ljps-frontend/pages/learning-journey/view/details/index.js

JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-58

[LJPS-58] View courses related to a skill

---

.github/workflows/CI_GCP.yml
backend/database/DatabaseDao.js
backend/service/__tests__/RolesService.test.js
backend/src/intTest/__tests__/LearningJourneyIntTest.integration.js
backend/src/intTest/__tests__/RolesIntTest.integration.js
backend/src/routes/learning-journey/LearningJourneyRouter.js

Add more tests for integration and unit 
None
None

[NO-JIRA] Create tests for roles

---

.gitignore
backend/database/DatabaseDao.js
backend/service/__tests__/SkillsService.test.js
backend/src/intTest/__tests__/AssignSkillToCourses.integration.js

[NO-JIRA] Update integration test for AssignCoursesToSkill

---

backend/database/DatabaseDao.js
backend/src/routes/learning-journey/LearningJourneyRouter.js

[NO-JIRA] Fix get learning journey bug in staging

---

ljps-frontend/components/LearningJourneyComponent/AddCourseModal.js
ljps-frontend/pages/learning-journey/view/DeleteModal.js

[NO-JIRA] fix url

---

.github/pull_request_template.md
README.md

Added readme file for submission
- Add readme
None
None

[NO-JIRA] Added readme file
